version: '3'
services:
  api:
    build: .
    ports:
     - "8080:5000"
    volumes:
     - .:/code
    depends_on:
     - mongo
    environment:
     - API_KEY=<INSERT YOUR KEY HERE>
     - MONGO_HOST=mongo
     - MONGO_PORT=27017
  mongo:
    image: "mongo:latest"
    ports:
     - "27017:27107"